apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/cloudflare
  prune: true
  sourceRef:
    kind: GitRepository
    name: core
