apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: north-south-wildcard
  namespace: istio-system
spec:
  selector:
    app: north-south-ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.sheffield.network"
