apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-helm-values
  namespace: cloudflare
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:+oyPYjImwweyAEgBEB5nGvGz40vwk7gT98X/8nPQq23a2APL+EvKAU1iFMOlSvpyO+y+RbYyfkRqg3BfHGJ0bbcbz1jp61EN3Pi5Va/eSt4nwxGO4hLApDgSFKsC+xfbKZsftB09LCOrYEB0h2lKOTfVYbgx7oVllCYhvziflAOZ1IVLDNWP31phPhh7SWT13IgPyl/zdzmd2gBuvtAidGP7bnAOpZH76m8wLCDizUtbQ1meZyR3/gEwnwhsl2KGZ5lWq55kr4NMd5hGYm8HvbftW9cI4RWe01aL7PtZOzU0C6Lq2WvSowSy33g/tLCpCEcagSTpVkj8srlKE1C+rXD4cmwk+sdN6H9XiSev5pvbmc5GD+hQHDUWgxg=,iv:6Vg5fG/DpwONWSY39id5Le0nOG18/72bDZYjGRs5UVk=,tag:q3k8hjALul5XrEjqzH4w9w==,type:str]
sops:
  age:
    - recipient: age1s08k5flasstpdy7xqphr970l85qwu08ypr4g3swcny8vt3q8vc8ssjam4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYjhBdkNURmZYM2dDR0NQ
        SDRIMXgyeDdFR3pta01NN0EreEVQRngwYW00Ci82M1FjRTRuL1o1RUd2QkhwREE3
        eWlsWitiaXdRWmVXbWUzRkFPUmZHU0EKLS0tIEd4UzVZU3RzaFJ4VzlhTCtwbmVv
        WUZEeE1qclhQeFU2WFFmMEZhd3BvYm8K0XS+L9y5WXT3/N7j10T5vyWfnZjbhKRH
        rIuNOcgp09gw9mdpH1Kd0Ozn7QhXmfE8Eblkvz6dBiVVjjc8de0Y1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-07T23:41:24Z"
  mac: ENC[AES256_GCM,data:CztHuD0+2pm9eDkex32pj1jJW3m8OwaZZoW+RZzBAY8y1MhxTxoxRmR8qS10VUKhiwDze6LwFdFxfQWleEXmqpma5d5+jbhFBuZDwSTIg8aZJg8McFjRxp4wwUTfozblW3t/NvVEmETqqO1EycNtq1pKV7Sf0tIYrOpKVPnvJJA=,iv:j6JGndEVyYd7+10ltEEX7uyyAfaI3E5eM9gRDobtxas=,tag:hNvV+p4R9ONsXUH8UoZDqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
