apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-helm-values
  namespace: cloudflare
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:W19qz1VG8rL3ovF5CfiBfyKDSy8lFbMdF7sBSzk1dKP2mdlLm/tYdeHtUj04Hleax9xZ5J0C8yuFzkMFwYMi++PHyd9V9+xkEaAPRrheSIQVL2ezTCH6DGiA32DH4uAlUw2bCvfPf16x3cXO1ucDKw6JhSw+j7y2Y5OrphmTMIVAmCEVAaWrfth5HRHS02sRDV2qWgBxpI738U7AEzavzMQNYU4C+dHRRoA8QH0tIk/utEkKLOHECNmSP4V3olvRvQh6wDgA86+aNk9fVziPsAOw0AC9TrU/L8J822jNEIibYqHZKP0yByWYi69S6nOUtS7MGCI21bB5B1S0DCezoPNWYC5QbMh6bUBYvd+nCzsPmQRd1uUQ4rDbDy8=,iv:YZqppYi9AunB4XDtn1CjbI4kJgqxKxVn6eyLOTwRV+I=,tag:gU8eJG5OGE9Di75fwrdvQA==,type:str]
sops:
  age:
    - recipient: age1s08k5flasstpdy7xqphr970l85qwu08ypr4g3swcny8vt3q8vc8ssjam4j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ1k5d2RQSkg1OVE4RHNt
        M09sNlhYRW1mUUhaT24xSXdtOGw3TGZsVEhVCnFoUHppRXVzQ2JiM1lkV0M2eHFq
        S0ZOWUMxbW05TU12LzhwVEpqSDJMajAKLS0tIFZnSWJSa0dOcThkQ3lFb0hZcDZa
        VlpWTkNzZFA1Wk1xU3NVVjN1aE9nYlkKTKb12xkQv665gXvDTm6yMcqae+Hx7uh2
        fSoVU/SW+1bxxMWg8fQNVuKiGqpkI/AvlCOvcsjqsKSMrV3ReIzg2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-08T00:22:08Z"
  mac: ENC[AES256_GCM,data:LLgPa1eBYYoS2iLg47v9DkgnlKZe7unzFZrghOY5/fhw282IAznboAELP0rxGRJyBXHZhfIYjxkenAmP95RmfTDOYnGc1Xd8L+nWpEDqEq08Q0Kh2UWvStCY5UcjGQz8/O9VuxMonRKPDcVZumT3npzqQ6KuT7vSla6LPh10RTs=,iv:QDaAmb+CribwBCVfFOowVAOFknHliGfoYe8cHLW0fPM=,tag:M3C/gLJQsBVjhEYffNOxig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
