apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-helm-values
  namespace: cloudflare
type: Opaque
data:
  values.yaml: |
    cloudflare:
      tunnelToken: ZXlKaElqb2lZekJoTURNeU0ySmlOV1ptTm1ObE1qaGtZemcwTkRVNU16TTBZelkyTURjaUxDSjBJam9pWkdJeFl6YzJOR010T0daa01TMDBZamxoTFdJME5UUXRPRFEyT0dReU5tTXhaV0kxSWl3aWN5STZJbHB0VlhoTlJHaHFUWHBaZEU0eVRUQk9lVEF3VG5wa2FreFhSbWhOVjFsMFRqSmFiRnB0UlROT1ZGWnFUMFJqTXlKOQ==
