apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-cluster
  namespace: flux-system
spec:
  targetNamespace: staging
  interval: 10m0s
  path: ./clusters/virtual
  prune: true
  sourceRef:
    kind: GitRepository
    name: core
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - target:
        kind: HelmRelease
        name: vcluster
      patch: |
        - op: replace
          path: /spec/releaseName
          value: staging
        - op: replace
          path: /spec/targetNamespace
          value: staging
    - target:
        kind: VirtualService
        name: vcluster
      patch: |
        - op: replace
          path: /spec/hosts/0
          value: staging.internal.m13t.dev
        - op: replace
          path: /spec/tls/0/match/0/sniHosts/0
          value: staging.internal.m13t.dev
        - op: replace
          path: /spec/tls/0/route/0/destination/host
          value: staging
