apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-init
  namespace: staging
type: Opaque
data:
  values.yaml: aW5pdDoKICBtYW5pZmVzdHM6IHwKICAgIGFwaVZlcnNpb246IHYxCiAgICBraW5kOiBOYW1lc3BhY2UKICAgIG1ldGFkYXRhOgogICAgICBuYW1lOiBmbHV4LXN5c3RlbQogICAgLS0tCiAgICBhcGlWZXJzaW9uOiB2MQogICAga2luZDogU2VjcmV0CiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogc29wcy1hZ2UKICAgICAgbmFtZXNwYWNlOiBmbHV4LXN5c3RlbQogICAgdHlwZTogT3BhcXVlCiAgICBkYXRhOgogICAgICBhZ2UuYWdla2V5OiBJeUJIYkc5aVlXd0tJeUJqY21WaGRHVmtPaUF5TURJekxURXlMVEEwVkRFMk9qQXlPalF4V2dvaklIQjFZbXhwWXlCclpYazZJR0ZuWlRGek1EaHJOV1pzWVhOemRIQmtlVGQ0Y1hCb2NqazNNR3c0TlhGM2RUQTRlWEJ5TkdjemMzZGpibms0ZG5RemNUaDJZemh6YzJwaGJUUnFDa0ZIUlMxVFJVTlNSVlF0UzBWWkxURkVOa3BNVTFNM1NGbElUVEJSV1V0VVUxTXlURlZSU0RNMFVVMVhPRlJZVEZrMVFWVlNNRVE0TWpNd1VESldVa3hSV2paUldGbFVTa3BGQ2c9PQogICAgLS0tCiAgICBhcGlWZXJzaW9uOiB2MQogICAga2luZDogU2VjcmV0CiAgICB0eXBlOiBPcGFxdWUKICAgIG1ldGFkYXRhOgogICAgICBuYW1lOiBmbHV4LXN5c3RlbQogICAgICBuYW1lc3BhY2U6IGZsdXgtc3lzdGVtCiAgICBkYXRhOgogICAgICBpZGVudGl0eTogTFMwdExTMUNSVWRKVGlCUVVrbFdRVlJGSUV0RldTMHRMUzB0Q2sxSlJ6SkJaMFZCVFVKQlIwSjVjVWRUVFRRNVFXZEZSMEpUZFVKQ1FVRnBRa2xIWlUxSlIySkJaMFZDUWtSQ1dXZzViMGdyUzBGRGIxUklNazlzTlVFS2FtMW1ZblJyYnpSTlptTnVhakJQY25SVlJWbGFjV1YwV0RCTVlYcHJiRk5LV1Zsd2FXbE5UREJtSzJsUlNsTm9Xa0ZPYVVGQlVpOVJkVlYzZEhReUx3cFlVSEpFTmpaUldESnhlRFprWTFCaVdtbDNSWFJRVDFsRVVYcFBTRGxvY3pWa1puUXhaVnBGY2tKRlZuUXpWakJhTkZJNWNDOXdLMDFaZDBkSlVrdENDamhVVGsxWmNVaHRNVEJ1TjNwMFIxRmxVM1ZQYVhGbmVtRjBiR1J5ZUVvemJFbzNVa1p2Y21SVVVrVlJlRWxITkRGdlEyWnBPRWs5Q2kwdExTMHRSVTVFSUZCU1NWWkJWRVVnUzBWWkxTMHRMUzBLCiAgICAgIGlkZW50aXR5LnB1YjogWldOa2MyRXRjMmhoTWkxdWFYTjBjRE00TkNCQlFVRkJSVEpXYWxwSVRtaE1XRTV2V1ZSSmRHSnRiSHBrU0VGNlQwUlJRVUZCUVVsaWJXeDZaRWhCZWs5RVVVRkJRVUpvUWtnNVF6VlVRekl6WWpsakszTlFjbkJDWm1GeVNIQXhkemwwYlV4QlV6QTROV2RPUkUwMFpqSkhlbXd4S3pOV05XdFRjMFZTVnpOa1dGSnVhRWd5Yml0dU5IaHFRVmxvUlc5SWVFMHdlR2x2WldKWVUyWjJUekJhUWpWTE5EWkxjVVJPY1RKV01uWkZibVZWYm5SRlYybDBNVTVGVWtSRloySnFWMmRLSzB4M1p6MDlDZz09CiAgICAgIGtub3duX2hvc3RzOiBaMmwwYUhWaUxtTnZiU0JsWTJSellTMXphR0V5TFc1cGMzUndNalUySUVGQlFVRkZNbFpxV2toT2FFeFlUbTlaVkVsMFltMXNlbVJJUVhsT1ZGbEJRVUZCU1dKdGJIcGtTRUY1VGxSWlFVRkJRa0pDUlcxTFUwVk9hbEZGWlhwUGJYaHJXazE1TjI5d1MyZDNSa0k1Ym10ME5WbFNjbGxOYWs1MVJ6Vk9PRGQxVW1kbk5rTk1jbUp2TlhkQlpGUXZlVFoyTUcxTFZqQlZNbmN3VjFveVdVSXZLeXRVY0c5amEyYzkK
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: staging-cluster
  namespace: flux-system
spec:
  releaseName: staging
  targetNamespace: staging
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: vcluster
  values:
    vcluster:
      image: rancher/k3s:v1.28.4-k3s1
    syncer:
      extraArgs:
        - --tls-san=staging.internal.m13t.dev
        - --out-kube-config-server=https://staging.internal.m13t.dev
    sync:
      nodes:
        enabled: true
        syncAllNodes: true
  valuesFrom:
    - kind: Secret
      name: cluster-init
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 1h0m0s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vcluster
  namespace: staging
spec:
  hosts:
    - staging.internal.m13t.dev
  gateways:
    - istio-system/vcluster
  tls:
    - match:
        - port: 443
          sniHosts:
            - staging.internal.m13t.dev
      route:
        - destination:
            host: staging
            port:
              number: 443
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod-cluster
  namespace: flux-system
spec:
  releaseName: production
  targetNamespace: production
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: vcluster
  values:
    vcluster:
      image: rancher/k3s:v1.28.4-k3s1
    syncer:
      extraArgs:
        - --tls-san=production.internal.m13t.dev
        - --out-kube-config-server=https://production.internal.m13t.dev
    sync:
      nodes:
        enabled: true
        syncAllNodes: true
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 1h0m0s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vcluster
  namespace: production
spec:
  hosts:
    - production.internal.m13t.dev
  gateways:
    - istio-system/vcluster
  tls:
    - match:
        - port: 443
          sniHosts:
            - production.internal.m13t.dev
      route:
        - destination:
            host: production
            port:
              number: 443
