apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-init
  namespace: staging
type: Opaque
data:
  values.yaml: aW5pdDoKICBtYW5pZmVzdHM6IHwtCiAgICBhcGlWZXJzaW9uOiB2MQogICAga2luZDogTmFtZXNwYWNlCiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogZmx1eC1zeXN0ZW0KICAgIC0tLQogICAgYXBpVmVyc2lvbjogdjEKICAgIGtpbmQ6IFNlY3JldAogICAgbWV0YWRhdGE6CiAgICAgIG5hbWU6IHNvcHMtYWdlCiAgICAgIG5hbWVzcGFjZTogZmx1eC1zeXN0ZW0KICAgIHR5cGU6IE9wYXF1ZQogICAgZGF0YToKICAgICAgYWdlLmFnZWtleTogSXlCSGJHOWlZV3dLSXlCamNtVmhkR1ZrT2lBeU1ESXpMVEV5TFRBMFZERTJPakF5T2pReFdnb2pJSEIxWW14cFl5QnJaWGs2SUdGblpURnpNRGhyTldac1lYTnpkSEJrZVRkNGNYQm9jamszTUd3NE5YRjNkVEE0ZVhCeU5HY3pjM2RqYm5rNGRuUXpjVGgyWXpoemMycGhiVFJxQ2tGSFJTMVRSVU5TUlZRdFMwVlpMVEZFTmtwTVUxTTNTRmxJVFRCUldVdFVVMU15VEZWUlNETTBVVTFYT0ZSWVRGazFRVlZTTUVRNE1qTXdVREpXVWt4UldqWlJXRmxVU2twRkNnPT0KICAgIC0tLQogICAgYXBpVmVyc2lvbjogdjEKICAgIGtpbmQ6IFNlY3JldAogICAgdHlwZTogT3BhcXVlCiAgICBtZXRhZGF0YToKICAgICAgbmFtZTogZmx1eC1zeXN0ZW0KICAgICAgbmFtZXNwYWNlOiBmbHV4LXN5c3RlbQogICAgZGF0YToKICAgICAgaWRlbnRpdHk6IExTMHRMUzFDUlVkSlRpQlFVa2xXUVZSRklFdEZXUzB0TFMwdENrMUpSekpCWjBWQlRVSkJSMEo1Y1VkVFRUUTVRV2RGUjBKVGRVSkNRVUZwUWtsSFpVMUpSMkpCWjBWQ1FrUkNXV2c1YjBnclMwRkRiMVJJTWs5c05VRUthbTFtWW5ScmJ6Uk5abU51YWpCUGNuUlZSVmxhY1dWMFdEQk1ZWHByYkZOS1dWbHdhV2xOVERCbUsybFJTbE5vV2tGT2FVRkJVaTlSZFZWM2RIUXlMd3BZVUhKRU5qWlJXREp4ZURaa1kxQmlXbWwzUlhSUVQxbEVVWHBQU0Rsb2N6VmtablF4WlZwRmNrSkZWblF6VmpCYU5GSTVjQzl3SzAxWmQwZEpVa3RDQ2poVVRrMVpjVWh0TVRCdU4zcDBSMUZsVTNWUGFYRm5lbUYwYkdSeWVFb3piRW8zVWtadmNtUlVVa1ZSZUVsSE5ERnZRMlpwT0VrOUNpMHRMUzB0UlU1RUlGQlNTVlpCVkVVZ1MwVlpMUzB0TFMwSwogICAgICBpZGVudGl0eS5wdWI6IFpXTmtjMkV0YzJoaE1pMXVhWE4wY0RNNE5DQkJRVUZCUlRKV2FscElUbWhNV0U1dldWUkpkR0p0Ykhwa1NFRjZUMFJSUVVGQlFVbGliV3g2WkVoQmVrOUVVVUZCUVVKb1FrZzVRelZVUXpJellqbGpLM05RY25CQ1ptRnlTSEF4ZHpsMGJVeEJVekE0TldkT1JFMDBaakpIZW13eEt6TldOV3RUYzBWU1Z6TmtXRkp1YUVneWJpdHVOSGhxUVZsb1JXOUllRTB3ZUdsdlpXSllVMloyVHpCYVFqVkxORFpMY1VST2NUSldNblpGYm1WVmJuUkZWMmwwTVU1RlVrUkZaMkpxVjJkS0sweDNaejA5Q2c9PQogICAgICBrbm93bl9ob3N0czogWjJsMGFIVmlMbU52YlNCbFkyUnpZUzF6YUdFeUxXNXBjM1J3TWpVMklFRkJRVUZGTWxacVdraE9hRXhZVG05WlZFbDBZbTFzZW1SSVFYbE9WRmxCUVVGQlNXSnRiSHBrU0VGNVRsUlpRVUZCUWtKQ1JXMUxVMFZPYWxGRlpYcFBiWGhyV2sxNU4yOXdTMmQzUmtJNWJtdDBOVmxTY2xsTmFrNTFSelZPT0RkMVVtZG5Oa05NY21Kdk5YZEJaRlF2ZVRaMk1HMUxWakJWTW5jd1Yxb3lXVUl2S3l0VWNHOWphMmM5Cg==
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: staging-cluster
  namespace: staging
spec:
  releaseName: staging
  targetNamespace: staging
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: vcluster
        namespace: flux-system
  values:
    vcluster:
      image: rancher/k3s:v1.28.4-k3s1
    # syncer:
    #   extraArgs:
    #     - --tls-san=staging.internal.m13t.dev
    #     - --out-kube-config-server=https://staging.internal.m13t.dev
    sync:
      nodes:
        enabled: true
        syncAllNodes: true
  valuesFrom:
    - kind: Secret
      name: cluster-init
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 1h0m0s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vcluster
  namespace: staging
spec:
  hosts:
    - staging.internal.m13t.dev
  gateways:
    - istio-system/vcluster
  tls:
    - match:
        - port: 443
          sniHosts:
            - staging.internal.m13t.dev
      route:
        - destination:
            host: staging
            port:
              number: 443
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod-cluster
  namespace: production
spec:
  releaseName: production
  targetNamespace: production
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: vcluster
        namespace: flux-system
  values:
    vcluster:
      image: rancher/k3s:v1.28.4-k3s1
    # syncer:
    #   extraArgs:
    #     - --tls-san=production.internal.m13t.dev
    #     - --out-kube-config-server=https://production.internal.m13t.dev
    sync:
      nodes:
        enabled: true
        syncAllNodes: true
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 1h0m0s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vcluster
  namespace: production
spec:
  hosts:
    - production.internal.m13t.dev
  gateways:
    - istio-system/vcluster
  tls:
    - match:
        - port: 443
          sniHosts:
            - production.internal.m13t.dev
      route:
        - destination:
            host: production
            port:
              number: 443
