apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/m13t-labs/k8s-flux-core
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/management
  prune: true
  sourceRef:
    kind: GitRepository
    name: core
  decryption:
    provider: sops
    secretRef:
      name: sops-age
