apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 60m0s
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux
