apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/fluxcd/flux-manifests
  ref:
    tag: latest
