apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the istio cni components
  name: istio-cni
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: cni
  targetNamespace: istio-system
  interval: 1h0m0s
  dependsOn:
    - name: istio-base
      namespace: flux-system
