apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the istio cni components
  name: istio-cni
  namespace: flux-system
spec:
  releaseName: cni
  targetNamespace: istio-system
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  # values:
  #   cni:
  #     cniBinDir: /usr/libexec/cni
  #     cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
  interval: 1h0m0s
  dependsOn:
    - name: istio-base
      namespace: flux-system
