apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the istio cni components
  name: istio-north-south-ingress
  namespace: flux-system
spec:
  releaseName: north-south-ingress
  targetNamespace: istio-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    service:
      type: ClusterIP
    autoscaling:
      minReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
  interval: 1h0m0s
  dependsOn:
    - name: istio-controller
      namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the istio cni components
  name: istio-east-west-ingress
  namespace: flux-system
spec:
  releaseName: east-west-ingress
  targetNamespace: istio-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    service:
      type: LoadBalancer
    autoscaling:
      minReplicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
  interval: 1h0m0s
  dependsOn:
    - name: istio-controller
      namespace: flux-system
