apiVersion: v1
kind: Secret
metadata:
  name: primary-credentials-logs
  namespace: monitoring
stringData:
  username: "750845"
  password: glc_eyJvIjoiOTk3NjE0IiwibiI6InN0YWNrLTc5Nzg0OS1obC1yZWFkLWFnZW50IiwiayI6IjJjOVM4MGxLVU83czVuRjU3RGtUNk1KOSIsIm0iOnsiciI6InByb2QtZXUtbm9ydGgtMCJ9fQ==
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: primary
  namespace: monitoring
  labels:
    agent: grafana-agent-logs
spec:
  clients:
  - url: https://logs-prod-025.grafana.net/loki/api/v1/push
    basicAuth:
      username:
        name: primary-credentials-logs
        key: username
      password:
        name: primary-credentials-logs
        key: password

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the LogsInstance CR
  podLogsNamespaceSelector: {}
  podLogsSelector:
    matchLabels:
      instance: primary
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    instance: primary
  name: kubernetes-pods
  namespace: monitoring
spec:
  pipelineStages:
    - docker: {}
  namespaceSelector:
    any: true
  selector:
    matchLabels: {}
